### ISSUE TITLE
Incorrect sizes when generating iOS icon sets

### ISSUE THREAD

**Issue by williamoconnorme** [kuyawa/AppIcons#2]
I'm exporting icons from an image that is 1024x1024 .PNG file to my AppIcon folder in my project, however I am receiving a lot of compiler warnings about incorrect dimensions for app icons.

Are you able to reproduce this issue?

Using Xcode 8.3.3

<img width="1455" alt="screen shot 2017-07-02 at 16 03 14" src="https://user-images.githubusercontent.com/978081/27771092-08f9ffca-5f40-11e7-8b1f-01fa0ce376c8.png">

**Comment by kuyawa** [comment]
Fixed in v3.2
